name: build lazygit

on:
  workflow_dispatch:
    inputs:
        pkgver:
          description: lazygit version to build

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CGO_ENABLED: 0
      GOOS: windows
      GOARCH: amd64
      GOAMD64: v3
      GOFLAGS: "-buildvcs=false -trimpath"
      pkgver: ${{ github.event.inputs.pkgver }}
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false

      - name: build lazygit 
        run: lazygit/build.sh
      
      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: lazygit 
          path: pkgdir/lazygit-${{ github.event.inputs.pkgver }}/lazygit.exe
